version: "3.3"
services:

  shortlink:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "shortlink"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      BASE_URL: http://localhost:3000
    networks:
      - shortlink_network

  postgres:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_DB: "shortlink"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - shortlink_network

networks:
  shortlink_network:
    driver: bridge